-- create user
BEGIN
   EXECUTE IMMEDIATE 'DROP USER TALEND_TASK3 CASCADE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1918 THEN
         RAISE;
      END IF;
END;
/

CREATE USER TALEND_TASK3 IDENTIFIED BY TALEND_TASK3
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users
TEMPORARY TABLESPACE temp
PROFILE default;

GRANT connect TO TALEND_TASK3;
GRANT resource TO TALEND_TASK3;
GRANT CREATE SYNONYM TO TALEND_TASK3;

-- create table
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TALEND_TASK3.LOADED_FILES';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE TALEND_TASK3.LOADED_FILES (
     filename varchar2(255)
);